### ISSUE TITLE
Placenta - Openload links not showing up as premium

### ISSUE THREAD

**Issue by Mastacc** [MrBlamo420/Project#18]
Openload and Streamango links found from sources like Flixanity, Preeputlocker, Fleanix, Viioz, Timewatch, m4UFree are not showing up as premium even though Real-Debrid supports them. It still requires a pair.

**Comment by MrBlamo420** [comment]
Cause those are nor real debrid scrapers

**Comment by Mastacc** [comment]
I get that, but shouldn't the addon choose what links are premium while populating the list and not in the individual scrapers?

**Comment by MrBlamo420** [comment]
No the addon doesnt touch the links after they populate thats the site and
resolver and just going and doing that for openload on those would be a
waste of time for just a LABEL use the debrid scrapers
