### ISSUE TITLE
Chappaai	forked from outdated version?

### ISSUE THREAD

**Issue by akuiraz** [MrBlamo420/Project#2]
It looks like you may have forked this project from an outdated version... the latest version released was a was 2.1.17dev ... it was a dev version with updates from Midraal.  I happen to have this copy if you want it, it would help to be starting from all the latest fixes... let me know

**Comment by iCanuck** [comment]
I wouldn't mind taking a look at that version

**Comment by teverz** [comment]
It is in the repo bud

Teverz
