### ISSUE TITLE
improving sources for tv episodes listed YYYYMMDD instead of s00e00 (late shows, etc)

### ISSUE THREAD

**Issue by jasonbuechler** [MrBlamo420/Project#20]
I just "fixed" the RLSBB scraper for an issue that's bugged me for a while: A long time ago, scene releases (I guess?) started using dates instead of season/ep serialization to ID episodes for certain shows, especially "late shows" that have tons of episodes.

I'd gotten into the habit of going to rlsbb and unrestricting links for shows I wanted with realdebrid and then watching via the RD kodi addon... but then I got to wondering why Placenta (etc) weren't picking up these easy-to-find episodes... and concluded the above paragraph.

So I added some failover code to try YYYYMMDD when s00e00 url/patterns fail to match rlsbb's listings and links. My modified rlsbb.py is in my fork: https://github.com/jasonbuechler/Blamo/blob/master/script.module.placenta/lib/resources/lib/sources/en/rlsbb.py

A quick search on rlsbb indicates it should now return results for at least these shows:
- Conan
- Saturday Kitchen
- watch what happens live
- seth meyers
- jimmy fallon
- jimmy kimmel
- james corden
- stephen colbert
- WWE NXT
- iMPACT Wrestling
- WWE Smackdown Live
- Naked News
- Vice News Tonight
- TMZ
- TMZ on TV
- Dateline
- Panorama
- Dispatches

One more question in case there's an easy option: why does the RLSBB scraper add links as debridOnly?

**Comment by KingPug75** [comment]
This explains why I've been having problems with colbert and vice news for many months now.  Nice job, I hope this gets merged in soon.

**Comment by jasonbuechler** [comment]
@KingPug75 thanks, man, it's nice to know I wasn't alone missing that stuff. I have an up-to-date zip if you want to just apply it over-top your current module with a install-from-zip: https://github.com/jasonbuechler/Blamo/blob/master/zips/script.module.placenta/script.module.placenta-1.6.1b.zip

**Comment by jasonbuechler** [comment]
Yeah, I noticed that myself when I first looked at it, but then noticed that's actually a typo/badly named utility on RLSBB's side -- it appears when you use either the bb or light search buttons. I don't recall its scraper needing to use that variable though, so... shrug :) 
![image](https://user-images.githubusercontent.com/34217071/43481933-2583f8f0-94bc-11e8-8241-5ba5822cb7ac.png)

**Comment by MrBlamo420** [comment]
right on and yea itll be good some site hehe

**Comment by MrBlamo420** [comment]
Oh and rlsbb is a debrid website thats why and if you turn to false uploadgig hosts show which is a paypal sub so best to return to true
