### ISSUE TITLE
(placenta scraper) bestmoviez not (?) working

### ISSUE THREAD

**Issue by jasonbuechler** [MrBlamo420/Project#29]
hey blamo lemme know if this or other issues are bothersome, and i can just hyu on twitter or something, k??

I'm not sure if it's just the kinda stuff I search for, or if the site changed something, but I haven't seen any results from this scraper. Their website is a complete mess, though, with entries clearly entered by hand... links in anchors, links in plain paragraph text, and links in pre tags... so it's impressive there's a scraper at all :p 
(I'm taking a look at it, but if I "fix" anything, it's likely to be... ugly ;)  )

**Comment by MrBlamo420** [comment]
Yea i went into it not long ago they changed their site up so much they really made it a mess if you can get it going cool and yea itll be ugly im aware hehe also got one in ds that was working but ive just not looked at it
