### ISSUE TITLE
Placenta not opening fix

### ISSUE THREAD

**Issue by KBug** [MrBlamo420/Project#3]
I was having the same issue as some other people with Placenta not opening. I was able to trace the problem back to the control.py file in the script.module.placenta. You're missing the '', on line 219 of the file for the def moderator. Once I added that, Placenta then opened. So the def moderator part should be:

def moderator():
netloc = [urlparse.urlparse(sys.argv[0]).netloc, '', 'script.wraith', 'plugin.video.chappaai', 'plugin.video.live.streamspro', 'plugin.video.phstreams', 'plugin.video.cpstreams', 'plugin.video.tinklepad', 'script.tvguide.fullscreen', 'script.tvguide.assassins']

**Comment by dokoab** [comment]
Seems to have been fixed, I think you can close this.

https://github.com/MrBlamo420/Project/commit/f5ce80920d7f5a32a697b70dd58548836e582287#diff-47edce8c647452a3199fc025a23137c6

But as another user, thanks for sharing the fix.
