### ISSUE TITLE
script.module.legendary 2.0

### ISSUE THREAD

**Issue by bjgood** [MrBlamo420/Project#31]
Hi blamo,
Your new script.module.legendary 2.0 has an error in it. In script.module.legendary/lib/resources/lib/modules/control.py all Legendary entries (except for the first one) need to be changed to legendary instead. At present, after installing Legendary, you get an error then you first try to open it. This fixes the error.

Have a good one.

**Comment by MrBlamo420** [comment]
Lol no thanks its garbage
