### ISSUE TITLE
Project "livecathup"

### ISSUE THREAD

**Issue by wwark** [MrBlamo420/Project#40]
Hello MrBlamo,

We (Sylvain and me) saw you use the same code in your github master%2Fplugin.video.livecatchup as our github https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore

What is the purpose to do that ? Can you please explain the goal?
Thanks for your return

**Comment by MrBlamo420** [comment]
Hey there not sure where i got it from its author isnt me i just added it as a section in a addon i have for people interested in that content if you'd like i can remove it...

**Comment by wwark** [comment]
Thank you. We appreciate the remove you done.
Thanks again.

**Comment by MrBlamo420** [comment]
No worries. Glad you contacted me
