### ISSUE TITLE
Unofficial version ?? or what's up ?

### ISSUE THREAD

**Issue by DjDiabolik** [MrBlamo420/Project#5]
I see this:
****://github.com/MXTV/wozbox/tree/master/plugin.video.blamo

It's see 2.4.4.1 but i see a zip 3.5.2......... it's a fork ?

**Comment by MrBlamo420** [comment]
Yes don't touch it

**Comment by DjDiabolik** [comment]
Thanks for info.......... 

Meantime last night i have installed and tested (if it's ok for my usage..because it's works whitout any problems )some addons from this repo:
I have installed "Death Stream" (it's this video.blamo right ?).... it's a good addons and working great but it's not the exactly addons i need.
I have choose it because i see it's contain a scrapers for rlsbb.ru but it's not the exactly things i need.
Right now i try to found a addons can simply scraping the site like "ReleaseBB" by Mr.Entertainment do..... i don't know if you know this addons and "Death Stream" using trakt.tv correctly but i thinks it's not the best solution for me :)

Meantime, as i already said, the addons it's works.... but it's not my ideal for now. Thanks for your works and i'm sure other can appreciate it better than me :)
